theme: jekyll-theme-minimal
title: Page Sizer
description: Google Docs add-on to to specify custom page sizes.
logo: https://raw.githubusercontent.com/burnnat/page-sizer/master/assets/chrome-web-store/PageSizer-Promo.png
show_downloads: false
